### ISSUE TITLE
df functionality: insert one row and display it at view

### ISSUE THREAD

**Issue by epogrebnyak** [zarak/explore-django#9]
@zarak - is this what you were looking for? is it still an open question?

**Comment by zarak** [comment]
Yes, it's still an open question. Actually, I am running into the same error as #7.

I am trying to run the command `python minimal.py makemigrations minimal`

```python
import sys
import os

from django.conf import settings
from django.conf.urls import url
from django.core.management import execute_from_command_line
from django.http import HttpResponse

BASE_DIR = ''


if not settings.configured:
    settings.configure(
        DEBUG=True,
        SECRET_KEY='A-random-secret-key!',
        ROOT_URLCONF=sys.modules[__name__],
        DATABASES = {
        'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
            }
        },
        INSTALLED_APPS = [
            'minimal.apps.MinimalConfig'
            ]
    )

# Configuration for the app named minimal
from django.apps import AppConfig
class MinimalConfig(AppConfig):
    name = 'minimal'
    verbose_name = "Minimal Django"

default_app_config = 'minimal.apps.MinimalConfig'


def index(request):
    return HttpResponse('<h1>A minimal Django response!</h1>')

urlpatterns = [
    url(r'^$', index),
]


# Create a test model
from django.db import models
class Student(models.Model):
    name = models.CharField(max_length=200)


if __name__ == '__main__':
    import django
    django.setup()

    execute_from_command_line(sys.argv)
    # Display some configured settings
    # print("Installed apps:", settings.INSTALLED_APPS)
    # print("Databases:", settings.DATABASES)
```

Traceback:
```
Traceback (most recent call last):
  File "minimal.py", line 50, in <module>
    class Student(models.Model):
  File "/Users/zarak/anaconda3/envs/py36/lib/python3.6/site-packages/django/db/models/base.py", line 110, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/Users/zarak/anaconda3/envs/py36/lib/python3.6/site-packages/django/apps/registry.py", line 247, in get_containing_app_config
    self.check_apps_ready()
  File "/Users/zarak/anaconda3/envs/py36/lib/python3.6/site-packages/django/apps/registry.py", line 125, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by epogrebnyak** [comment]
Let me try replicate that

**Comment by zarak** [comment]
If I put this
```python
from django.apps import apps
apps.populate(settings.INSTALLED_APPS)
```
after 
`default_app_config = 'minimal.apps.MinimalConfig'`
it just freezes
```
^CTraceback (most recent call last):
  File "minimal.py", line 38, in <module>
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/zarak/anaconda3/envs/py36/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/zarak/anaconda3/envs/py36/lib/python3.6/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/Users/zarak/anaconda3/envs/py36/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 936, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 936, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/zarak/Documents/Work/explore-django/minimal-django/minimal.py", line 38, in <module>
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/zarak/anaconda3/envs/py36/lib/python3.6/site-packages/django/apps/registry.py", line 71, in populate
    with self._lock:
KeyboardInterrupt
```

**Comment by zarak** [comment]
I made [some progress](e0ca0b010827bdd4382414051766da5745259b49) - there's a crude working version in the `project` folder.

**edit**: That is, the migrations now run successfully.

I'll work on hooking the model up to the views next.

**Comment by epogrebnyak** [comment]
Somthing like ```from questions  import Questions``` is also needed in a file?

**Comment by epogrebnyak** [comment]
In the full-app cod eI have:

```
from datapoint.models import Datapoint


class DatapointViewSet(viewsets.ModelViewSet):
    queryset = Datapoint.objects.all()
    #...
```
<https://github.com/mini-kep/full-app/blob/master/datapoint/views.py>

**Comment by zarak** [comment]
When I try to import with `from minimal.models import Question` I get this error:

```
Traceback (most recent call last):
  File "min.py", line 27, in <module>
    from minimal.models import Question
  File "/Users/zarak/Documents/Work/explore-django/project/minimal/models.py", line 3, in <module>
    class Question(models.Model):
  File "/Users/zarak/anaconda3/envs/py36/lib/python3.6/site-packages/django/db/models/base.py", line 110, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/Users/zarak/anaconda3/envs/py36/lib/python3.6/site-packages/django/apps/registry.py", line 247, in get_containing_app_config
    self.check_apps_ready()
  File "/Users/zarak/anaconda3/envs/py36/lib/python3.6/site-packages/django/apps/registry.py", line 125, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by zarak** [comment]
Thank you for the reference to `Datapoint`. I will try using that.

**Comment by epogrebnyak** [comment]
As for the error, Django really fights for its integrity, right? )
